index:
    path: /{page}
    controller: App\Controller\HomeController::index
    methods : "GET"
    defaults : {"page": "1"}
home_show:
    path : home/{slug}
    controller: App\Controller\HomeController::show
    requirements: {"slug": "about|privacy"}
contact :
    path : home/contact
    controller: App\Controller\HomeController::show_contact
contact_success :
    path : home/contact_success
    controller : App\Controller\HomeController::contact_submit
search :
  path : /home/search
  controller : App\Controller\HomeController::search
register :
    path : /user/register
    controller : App\Controller\UsersController::register
login :
    path : /user/login
    controller : App\Controller\UsersController::login
profile : 
    path: /user/profile
    controller : App\Controller\UsersController::profile