index:
    path: /{_locale}/{page}
    controller: App\Controller\HomeController::index
    methods : "GET"
    defaults : {"page": "1",_locale : 'en'}
    requirements:
        _locale: 'en|hi'
home_show:
    path : /{_locale}/home/{slug}
    controller: App\Controller\HomeController::show
    requirements: {"slug": "about|privacy", _locale: 'en|hi'}
    defaults : 
        _locale : 'en'
contact :
    path : /{_locale}/home/contact
    controller: App\Controller\HomeController::show_contact
    requirements:
        _locale: 'en|hi'
    defaults : 
        _locale : 'en'
contact_success :
    path : /{_locale}/home/contact_success
    controller : App\Controller\HomeController::contact_submit
    requirements:
        _locale: 'en|hi'
    defaults : 
        _locale : 'en'
search :
    path : /{_locale}/home/search
    controller : App\Controller\HomeController::search
    requirements:
        _locale: 'en|hi'
    defaults : 
        _locale : 'en'
register :
    path : /{_locale}/user/register
    controller : App\Controller\UsersController::register
    requirements:
        _locale: 'en|hi'
    defaults : 
        _locale : 'en'
login :
    path : /{_locale}/user/login
    controller : App\Controller\UsersController::login
    requirements:
        _locale: 'en|hi'
    defaults : 
        _locale : 'en'
profile : 
    path: /{_locale}/user/profile
    controller : App\Controller\UsersController::profile
    requirements:
        _locale: 'en|hi'
    defaults : 
        _locale : 'en'
admin : 
    path: /{_locale}/admin/list/{page}
    controller : App\Controller\Admin\MovieController::list
    requirements:
        _locale: 'en|hi'
    defaults : {"page": "1",_locale : 'en'}
addmovie :
    path: /{_locale}/admin/addmovie
    controller : App\Controller\Admin\MovieController::new
    requirements:
        _locale: 'en|hi'
    defaults : 
        _locale : 'en'
editmovie : 
    path: /{_locale}/admin/editmovie/{id}
    controller : App\Controller\Admin\MovieController::edit
    requirements:
        _locale: 'en|hi'
    defaults : 
        _locale : 'en'
deletemovie : 
    path: /{_locale}/admin/deletemovie/{id}
    controller : App\Controller\Admin\MovieController::delete
    requirements:
        _locale: 'en|hi'
    defaults : 
        _locale : 'en'
admin_category :
    path: /{_locale}/admin/category/{page}
    controller : App\Controller\Admin\CategoryController::list
    requirements:
        _locale: 'en|hi'
    defaults : {"page": "1",_locale : 'en'}
admin_country :
    path: /{_locale}/admin/country/{page}
    controller : App\Controller\Admin\CountryController::list
    requirements:
        _locale: 'en|hi'
    defaults : {"page": "1",_locale : 'en'}
addcountry :
    path: /{_locale}/admin/addcountry
    controller : App\Controller\Admin\CountryController::new
    requirements:
        _locale: 'en|hi'
    defaults : 
        _locale : 'en'
editcountry : 
    path: /{_locale}/admin/editcountry/{id}
    controller : App\Controller\Admin\CountryController::edit
    requirements:
        _locale: 'en|hi'
    defaults : 
        _locale : 'en'
deletecountry : 
    path: /{_locale}/admin/deletecountry/{id}
    controller : App\Controller\Admin\CountryController::delete
    requirements:
        _locale: 'en|hi'
    defaults : 
        _locale : 'en'
admin_state :
    path: /{_locale}/admin/state/{page}
    controller : App\Controller\Admin\StateController::list
    requirements:
        _locale: 'en|hi'
    defaults : {"page": "1",_locale : 'en'}